# Generated by Django 4.0.6 on 2022-07-21 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
    ]
