# Generated by Django 4.0.6 on 2022-07-22 01:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0003_revisao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisao',
            name='Data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
