# Generated by Django 4.0.6 on 2022-07-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0004_alter_revisao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='Data_Hora_Fim',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='KM_Final',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
