# Generated by Django 4.0.6 on 2022-07-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0005_alter_viagem_data_hora_fim_alter_viagem_km_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='destino',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
