# Generated by Django 4.0.6 on 2022-08-03 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0009_alter_viagem_data_hora_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='veiculo',
            field=models.ForeignKey(limit_choices_to={'status': 'LIVRE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculo.veiculo'),
        ),
    ]
