# Generated by Django 4.1 on 2022-08-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0010_alter_viagem_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisao',
            name='KM',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='KM_Revisao',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='kilometragem',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='KM_Final',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='KM_Inicial',
            field=models.FloatField(default=0),
        ),
    ]
