# Generated by Django 4.1 on 2022-08-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0011_alter_revisao_km_alter_veiculo_km_revisao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='imagens_carros_viagens'),
        ),
    ]
